name: '02 - Eventos'
on: 
    push:
    pull_request:
    schedule:
      - cron: "55 17 * * *"
    workflow_dispatch:
jobs:
    echo:
      name: "ShowTriggerJob"
      runs-on: ubuntu-latest
      steps:
        - name: "ShowTrigger"
          run: |
            echo "Evento : ${{ github.event_name }}"