name: '02 - Eventos'
on: 
    push:
    pull_request:
    schedule:
      - cron: "55 17 * * *"
    workflow_dispatch:
jobs:
    ShowTrigger:
      name: "ShowTriggerJob"
      runs-on: ubuntu-latest
      steps:
        - name: ShowTrigger
          run: "Evento que desencadenó el workflow: ${{ github.event_name }}"